/**
 * Pixel art 12×12 ala Aseprite, ditulis langsung sebagai data:
 * tiap sprite adalah 12 baris string, tiap karakter = 1 piksel
 * dari PALETTE ('.' = transparan). Di-render tajam lewat SVG
 * shape-rendering="crispEdges" — nol file aset, tetap offline.
 *
 * Bangunan & dekorasi punya varian sprite per level (mis. farm1..farm3).
 */

export const PALETTE: Record<string, string> = {
  o: '#453227', // outline gelap
  w: '#a1662f', // kayu
  W: '#6e441e', // kayu gelap
  c: '#f0e0b8', // dinding krem
  r: '#d95763', // atap merah
  R: '#a93b4a', // atap merah gelap
  s: '#aab6bf', // batu
  S: '#77848e', // batu gelap
  g: '#6abe30', // daun
  G: '#37946e', // daun gelap
  e: '#99e550', // hijau muda
  y: '#f7d51d', // jerami/gandum
  Y: '#e8a33d', // emas
  n: '#8f563b', // tanah
  b: '#5b6ee1', // biru
  B: '#3f3f74', // biru gelap
  q: '#5fcde4', // air
  Q: '#3f9fd6', // air gelap
  m: '#ffffff', // putih
  f: '#d77bba', // bunga pink
  t: '#847e87', // abu patung
  l: '#ffe9a3', // cahaya lentera
};

const S = (raw: string): string[] =>
  raw
    .trim()
    .split('\n')
    .map((row) => row.trim().padEnd(12, '.').slice(0, 12))
    .concat(Array(12).fill('............'))
    .slice(0, 12);

export const SPRITES: Record<string, string[]> = {
  // ---------- alam ----------
  grass: S(`
    ............
    ............
    ...e........
    ..eGe.......
    ............
    ........e...
    .......eGe..
    ............
    ..e.........
    .eGe........
    ............
    ............
  `),
  tree: S(`
    ....GGGG....
    ...GggggG...
    ..GggggggG..
    ..GgeggegG..
    ..GggggggG..
    ...GggggG...
    ....GGGG....
    .....ww.....
    .....ww.....
    ....wWWw....
    ............
    ............
  `),
  pine: S(`
    .....GG.....
    ....gGGg....
    ...gGGGGg...
    ....gGGg....
    ...gGGGGg...
    ..gGGGGGGg..
    ...gGGGGg...
    ..gGGGGGGg..
    .gGGGGGGGGg.
    .....ww.....
    .....ww.....
    ............
  `),
  flower: S(`
    ............
    ...f...m....
    ..fff.mmm...
    ...f...m....
    ............
    .m.......f..
    mmm.....fff.
    .m.......f..
    ............
    ....f.......
    ...fff......
    ....f.......
  `),
  house: S(`
    ............
    ....rrrr....
    ...rrrrrr...
    ..rrrrrrrr..
    .rRrrrrrrRr.
    ..cccccccc..
    ..cccccccc..
    ..ccBBcccc..
    ..ccBBccyy..
    ..ccBBccyy..
    ..cccccccc..
    ............
  `),

  // ---------- ladang ----------
  farm1: S(`
    ............
    ............
    ............
    .oooooooooo.
    .onnnnnnnno.
    .onenenenno.
    .onnnnnnnno.
    .onenenenno.
    .onnnnnnnno.
    .oooooooooo.
    ............
    ............
  `),
  farm2: S(`
    ............
    ............
    .oooooooooo.
    .onnnnnnnno.
    .ogngngngno.
    .onnnnnnnno.
    .ogngngngno.
    .onnnnnnnno.
    .oooooooooo.
    ..w......w..
    ............
    ............
  `),
  farm3: S(`
    ............
    ..y.y.y.y...
    .oooooooooo.
    .oyyyyyyyyo.
    .oYyYyYyYyo.
    .oyyyyyyyyo.
    .oYyYyYyYyo.
    .oyyyyyyyyo.
    .oooooooooo.
    ..w......w..
    ............
    ............
  `),

  // ---------- sumur ----------
  well1: S(`
    ............
    ............
    ............
    ....ssss....
    ...sSqqSs...
    ...sqqqqs...
    ...sSqqSs...
    ....ssss....
    ............
    ............
    ............
    ............
  `),
  well2: S(`
    ............
    ...w....w...
    ...wwwwww...
    ...w....w...
    ...wssssw...
    ...sSqqSs...
    ...sqqqqs...
    ...sSqqSs...
    ....ssss....
    ............
    ............
    ............
  `),
  well3: S(`
    ....bbbb....
    ...bbbbbb...
    ..bBbbbbBb..
    ...w....w...
    ...w.yy.w...
    ...wssssw...
    ...sSqqSs...
    ...sqqqqs...
    ...sSqqSs...
    ....ssss....
    ............
    ............
  `),

  // ---------- balai desa ----------
  hall1: S(`
    ............
    ............
    ....wwww....
    ...wwwwww...
    ..wWWWWWWw..
    ..occcccco..
    ..occcccco..
    ..ocBBccco..
    ..ocBBccco..
    ..occcccco..
    ..oooooooo..
    ............
  `),
  hall2: S(`
    ............
    ....wwwww...
    ...wwwwwww..
    ..wWWWWWWWw.
    ..occccccco.
    ..obbcccbbo.
    ..occccccco.
    ..ocBBcccco.
    ..ocBBcccco.
    ..occccccco.
    ..ooooooooo.
    ............
  `),
  hall3: S(`
    ....YYYY....
    ...wwwwww...
    ..wwwwwwww..
    .wWWWWWWWWw.
    .occcccccco.
    .obbccccbbo.
    .occcccccco.
    .occBBBBcco.
    .occBBBBcco.
    .occcccccco.
    .oooooooooo.
    ............
  `),

  // ---------- pasar ----------
  market1: S(`
    ............
    ............
    ..rmrmrmrm..
    ..rmrmrmrm..
    ..w......w..
    ..w.yyyy.w..
    ..w.yYyY.w..
    ..w......w..
    ..wwwwwwww..
    ............
    ............
    ............
  `),
  market2: S(`
    ............
    .rmrmrmrmrm.
    .rmrmrmrmrm.
    .w........w.
    .w.yy..gg.w.
    .w.yY..gG.w.
    .w........w.
    .wwwwwwwwww.
    ...w....w...
    ............
    ............
    ............
  `),
  market3: S(`
    .....YY.....
    .rmrmrmrmrm.
    .rmrmrmrmrm.
    .w........w.
    .w.yy.f.gg.w
    .w.yY.f.gG.w
    .w........w.
    .wwwwwwwwww.
    ...w....w...
    ............
    ............
    ............
  `),

  // ---------- kuil ----------
  temple1: S(`
    ............
    ............
    .rrrrrrrrrr.
    ..r......r..
    .rrrrrrrrrr.
    ..r......r..
    ..r......r..
    ..r......r..
    ..r......r..
    .rr......rr.
    ............
    ............
  `),
  temple2: S(`
    ............
    .RRRRRRRRRR.
    .rrrrrrrrrr.
    ..r......r..
    ..rrrrrrrr..
    ..r......r..
    ..r......r..
    ..r......r..
    ..r......r..
    .rr......rr.
    ............
    ............
  `),
  temple3: S(`
    .YYYYYYYYYY.
    .rrrrrrrrrr.
    ..r......r..
    ..rrrrrrrr..
    ..r......r..
    ..r.l..l.r..
    ..r......r..
    ..r......r..
    ..r......r..
    .rr......rr.
    ............
    ............
  `),

  // ---------- menara jaga ----------
  tower1: S(`
    ............
    ............
    ....ssss....
    ....s..s....
    ....ssss....
    ....sSSs....
    ....ssss....
    ....sSSs....
    ....ssss....
    ...ssssss...
    ............
    ............
  `),
  tower2: S(`
    .....r......
    .....rr.....
    .....s......
    ....ssss....
    ....s..s....
    ....ssss....
    ....sSSs....
    ....ssss....
    ....sSSs....
    ....ssss....
    ...ssssss...
    ............
  `),

  // ---------- kastil ----------
  castle1: S(`
    .b........b.
    .ss..ss..ss.
    .ss..ss..ss.
    .ssssssssss.
    .sSSsSSsSSs.
    .ssssssssss.
    .ss.ssss.ss.
    .ss.sBBs.ss.
    .ssssBBssss.
    .ssssssssss.
    ............
    ............
  `),

  // ---------- dekorasi: taman bunga ----------
  garden1: S(`
    ............
    ............
    ....f.......
    ...fff..m...
    ....f..mmm..
    ........m...
    ..e.........
    .eGe...f....
    ......fff...
    .......f....
    ............
    ............
  `),
  garden2: S(`
    ............
    .oooooooooo.
    .oeefeefeeo.
    .oefffefffo.
    .oeefeefeeo.
    .oefffefffo.
    .oeefeefeeo.
    .oooooooooo.
    ............
    ............
    ............
    ............
  `),
  garden3: S(`
    .oooooooooo.
    .omffemffeo.
    .offfmfffmo.
    .omffemffeo.
    .offfmfffmo.
    .omffemffeo.
    .oooooooooo.
    ....o..o....
    ............
    ............
    ............
    ............
  `),

  // ---------- dekorasi: lentera ----------
  lantern1: S(`
    ............
    ............
    ............
    .....ss.....
    ....ssss....
    .....ll.....
    ....ssss....
    .....ss.....
    .....ss.....
    ....ssss....
    ............
    ............
  `),
  lantern2: S(`
    ............
    .....ss.....
    ....ssss....
    ....l..l....
    ...l.ll.l...
    ....l..l....
    ....ssss....
    .....ss.....
    .....ss.....
    ....ssss....
    ...ssssss...
    ............
  `),
  lantern3: S(`
    .....ss.....
    ....ssss....
    ...l....l...
    ..l.llll.l..
    ..l.llll.l..
    ...l....l...
    ....ssss....
    .....ss.....
    .....ss.....
    ....ssss....
    ...ssssss...
    ............
  `),

  // ---------- dekorasi: patung ----------
  statue1: S(`
    ............
    ............
    ............
    .....tt.....
    .....tt.....
    ....tttt....
    .....tt.....
    ....tttt....
    ...tttttt...
    ............
    ............
    ............
  `),
  statue2: S(`
    ............
    .....tt.....
    .....tt.....
    ....tttt..w.
    .....tt...w.
    ....tttt..w.
    ....t..t....
    ....t..t....
    ...tttttt...
    ..tttttttt..
    ............
    ............
  `),
  statue3: S(`
    .....YY.....
    .....YY.....
    ....YYYY....
    .....YY.....
    ....YYYY....
    ....Y..Y....
    ....Y..Y....
    ...ssssss...
    ..sSSSSSSs..
    .ssssssssss.
    ............
    ............
  `),

  // ---------- dekorasi: kolam ----------
  pond1: S(`
    ............
    ............
    ............
    ....qqqq....
    ...qqqqqq...
    ...qQqqQq...
    ...qqqqqq...
    ....qqqq....
    ............
    ............
    ............
    ............
  `),
  pond2: S(`
    ............
    ............
    ...qqqqqq...
    ..qqqqqqqq..
    ..qQqgqqQq..
    ..qqqggqqq..
    ..qQqqqqQq..
    ..qqqqqqqq..
    ...qqqqqq...
    ............
    ............
    ............
  `),
  pond3: S(`
    ............
    ..sqqqqqqs..
    ..qqqfqqqq..
    .qqqfffqqqq.
    .qQqqfqqgQq.
    .qqqggqqggq.
    .qQqqqqqqQq.
    ..qqqqqqqq..
    ..sqqqqqqs..
    ............
    ............
    ............
  `),

  // ---------- dekorasi: kincir angin ----------
  windmill1: S(`
    ..w...w.....
    ...w.w......
    ....o.......
    ...w.w......
    ..w...w.....
    ....cc......
    ....cc......
    ....cc......
    ...cccc.....
    ..cccccc....
    ............
    ............
  `),
  windmill2: S(`
    ..w....w....
    ...w..w.....
    ....oo......
    ...w..w.....
    ..w....w....
    ....rr......
    ...cccc.....
    ...cccc.....
    ...cccc.....
    ..cccccc....
    ............
    ............
  `),
  windmill3: S(`
    .w.....w....
    ..w...w.....
    ...wYYw.....
    ...YooY.....
    ..w...w.....
    .w.....w....
    ....rr......
    ...cccc.....
    ...cBBc.....
    ...cccc.....
    ..cccccc....
    ............
  `),

  // ---------- dekorasi: gerbang pelangi ----------
  rainbow1: S(`
    ............
    ............
    ............
    ....rrrr....
    ...ryyyyr...
    ..ry....yr..
    ..r......r..
    ............
    ............
    ............
    ............
    ............
  `),
  rainbow2: S(`
    ............
    ............
    ...rrrrrr...
    ..ryyyyyyr..
    .ryggggggyr.
    .rg......gr.
    .r........r.
    ............
    ............
    ............
    ............
    ............
  `),
  rainbow3: S(`
    ...rrrrrr...
    ..ryyyyyyr..
    .ryggggggyr.
    .ygbbbbbbgy.
    .gb......bg.
    mm........mm
    mmm......mmm
    .m........m.
    ............
    ............
    ............
    ............
  `),
};

/** Ambil sprite dengan fallback: coba level diminta, turun sampai level 1. */
export function spriteKey(base: string, level: number): string {
  for (let l = Math.max(1, level); l >= 1; l--) {
    if (SPRITES[`${base}${l}`]) return `${base}${l}`;
  }
  return SPRITES[base] ? base : 'grass';
}
